.TH YAPS 1 "V 0.92 21. May 1997"
.SH NAME
yaps \- Yet Another Pager Software
.SH SYNOPSIS
yaps [opts] [parameter]
.SH DESCRIPTION
Sorry, this manual page is currently more or less empty. See the user
documentation
.B yaps.html
or
.BR yaps.doc .
.SH AUTHOR
Written and copyrighted by Ulrich Dessauer, Germering, Germany. See file
.B COPYRIGHT
and
.B COPYING.GPL
for details on usage and warrenty.
.SH BUGS
Perhaps a lot as this is considered as alpha software.
